# generated by ChatGPT - it's very powerful chat bot \U0001f913
# @param {Integer[]} points
# @return {Integer}
def max_area(points)
max_area = 0
left = 0
right = points.length - 1
while left < right
  max_area = [max_area, (right - left) * [points[left], points[right]].min].max
  if points[left] < points[right]
    left += 1
  else
    right -= 1
  end
end
max_area
end
# [1, 2, 1]


